; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino

[env:remote]
platform = atmelavr
board = pro8MHzatmega328
build_flags = -DREMOTE -D_debug
monitor_speed = 115200
build_src_filter = 
  +<*>            ; Start by including all files in the src directory
  -<boardv1.cpp>  ; Exclude a other board file
	-<boardv2.cpp>  ; Exclude a other board file
lib_deps = 
	nrf24/RF24@^1.5.0
	arduino-libraries/Servo

[env:remote_prod]
platform = atmelavr
board = pro8MHzatmega328
build_flags = -DREMOTE -DCYCLE_FREQ=50
monitor_speed = 115200
build_src_filter = 
  +<*>            ; Start by including all files in the src directory
  -<boardv1.cpp>  ; Exclude a other board file
	-<boardv2.cpp>  ; Exclude a other board file
lib_deps = 
	nrf24/RF24@^1.5.0
	arduino-libraries/Servo

[env:boardv2]
platform = atmelavr
board = pro8MHzatmega328
build_flags = -D_debug
monitor_speed = 115200
build_src_filter = 
  +<*>            ; Start by including all files in the src directory
  -<boardv1.cpp>  ; Exclude a other board file
lib_deps = 
	arduino-libraries/Servo
	nrf24/RF24@^1.5.0
	finallyfunctional/VescUart@^1.1.1

[env:boardv2_prod]
platform = atmelavr
board = pro8MHzatmega328
build_flags = -DCYCLE_FREQ=50  
monitor_speed = 115200
build_src_filter = 
  +<*>            ; Start by including all files in the src directory
  -<boardv1.cpp>  ; Exclude a other board file
lib_deps = 
	arduino-libraries/Servo
	nrf24/RF24@^1.5.0
	finallyfunctional/VescUart@^1.1.1

[env:boardv2_prod_debug]
platform = atmelavr
board = pro8MHzatmega328
build_flags = -DCYCLE_FREQ=50 -D_debug
monitor_speed = 115200
build_src_filter = 
  +<*>            ; Start by including all files in the src directory
  -<boardv1.cpp>  ; Exclude a other board file
lib_deps = 
	arduino-libraries/Servo
	nrf24/RF24@^1.5.0
	finallyfunctional/VescUart@^1.1.1


[env:boardv1]
platform = atmelavr
board = nanoatmega328new
build_flags = -D_debug
monitor_speed = 115200
build_src_filter = 
  +<*>            ; Start by including all files in the src directory
  -<boardv2.cpp>  ; Exclude a other board file
lib_deps = 
	arduino-libraries/Servo
	nrf24/RF24@^1.5.0
	finallyfunctional/VescUart@^1.1.1

[env:boardv1_prod]
platform = atmelavr
board = nanoatmega328new
build_flags = -DCYCLE_FREQ=50  
monitor_speed = 115200
build_src_filter = 
  +<*>            ; Start by including all files in the src directory
  -<boardv2.cpp>  ; Exclude a other board file
lib_deps = 
	arduino-libraries/Servo
	nrf24/RF24@^1.5.0
	finallyfunctional/VescUart@^1.1.1